[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = [
  "-Lnative=${env:XWIN_ROOT}/crt/lib/x86_64",
  "-Lnative=${env:XWIN_ROOT}/sdk/lib/ucrt/x86_64",
  "-Lnative=${env:XWIN_ROOT}/sdk/lib/um/x86_64",
]
